src/Fiona/Geek2geek/CoreBundle/Entity/Geek.php
<?php

namespace Fiona\Geek2geek\CoreBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Geek
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Fiona\Geek2geek\CoreBundle\Repository\GeekRepository")
 */
class Geek
{

    public static $UPLOAD_DIR = "uploads/user/";

    public function getPhoto() {

        $pic = self::$UPLOAD_DIR.$this->id.".jpg";

        if (!file_exists($pic)) {
            return "resources/user/".strtolower($this->gender).".png";
        }

        return $pic;
    }


    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="firstname", type="string", length=255)
     */
    private $firstname;

    /**
     * @var string
     *
     * @ORM\Column(name="lastname", type="string", length=255)
     */
    private $lastname;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="gender", type="string", length=255)
     */
    private $gender;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="datesign", type="datetime")
     */
    private $datesign;


    /**
     * @ORM\ManyToMany(targetEntity="Interest", mappedBy="geeks")
     *
     */
    private $interests;


    /**
     * @ORM\OneToMany(targetEntity="Visit", mappedBy="geek")
     *
     */
    private $visits;



    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     *
     * @return Geek
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
     * Get firstname
     *
     * @return string
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     *
     * @return Geek
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get lastname
     *
     * @return string
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Set email
     *
     * @param string $email
     *
     * @return Geek
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set gender
     *
     * @param string $gender
     *
     * @return Geek
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
     * Get gender
     *
     * @return string
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set datesign
     *
     * @param \DateTime $datesign
     *
     * @return Geek
     */
    public function setDatesign($datesign)
    {
        $this->datesign = $datesign;

        return $this;
    }

    /**
     * Get datesign
     *
     * @return \DateTime
     */
    public function getDatesign()
    {
        return $this->datesign;
    }
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->interests = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add interest
     *
     * @param \Fiona\Geek2geek\CoreBundle\Entity\Interest $interest
     *
     * @return Geek
     */
    public function addInterest(\Fiona\Geek2geek\CoreBundle\Entity\Interest $interest)
    {
        $this->interests[] = $interest;

        return $this;
    }

    /**
     * Remove interest
     *
     * @param \Fiona\Geek2geek\CoreBundle\Entity\Interest $interest
     */
    public function removeInterest(\Fiona\Geek2geek\CoreBundle\Entity\Interest $interest)
    {
        $this->interests->removeElement($interest);
    }

    /**
     * Get interests
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getInterests()
    {
        return $this->interests;
    }

    /**
     * Add visit
     *
     * @param \Fiona\Geek2geek\CoreBundle\Entity\Visit $visit
     *
     * @return Geek
     */
    public function addVisit(\Fiona\Geek2geek\CoreBundle\Entity\Visit $visit)
    {
        $this->visits[] = $visit;

        return $this;
    }

    /**
     * Remove visit
     *
     * @param \Fiona\Geek2geek\CoreBundle\Entity\Visit $visit
     */
    public function removeVisit(\Fiona\Geek2geek\CoreBundle\Entity\Visit $visit)
    {
        $this->visits->removeElement($visit);
    }

    /**
     * Get visits
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getVisits()
    {
        return $this->visits;
    }

    public function hasInterest($id) {
        foreach($this->getInterests() as $interest) {
            if ($interest->getId() == $id) {
                return true;
            }
        }

        return false;
    }
}

src/Fiona/Geek2geek/CoreBundle/Resources/views/Layout/geekitem.html.twig
{% for geek in geeks %}
    <section class="bloc">

        <a href="{{ path('fiona_geek2geek_core_profile',{id:geek.id}) }}">
            <img src="{{ asset(geek.photo) }}"  class="avatar">
        </a>

        <header>

            {% set avatar = geek.gender|upper == 'FEMALE' ? 'images/female.png' : 'images/male.png' %}

            <a href="{{ path('fiona_geek2geek_core_profile',{id:geek.id}) }}" style="background: url('{{ asset(avatar) }}') no-repeat 0 3px;padding-left:30px;">
            {{ geek.firstname }} {{ geek.lastname }}
            </a>
			
			<span class="right">
				Register on {{ geek.datesign|date('d/m/Y') }}
			</span>
        </header>

        <section>



            {% if geek.interests|length <= 0 %}
                This person has no center of interest
            {% endif %}

            {% for interest in geek.interests %}
                <div class="interet"><div class="vign"></div>{{ interest.label }}</div>
            {% endfor %}


        </section>

    </section>
{% endfor %}

src/Fiona/Geek2geek/CoreBundle/Resources/views/Layout/leftsearch.html.twig
<aside>
    <header>
        <img src="{{ asset('images/searchiconbar.png') }}">
        Search
    </header>

    <section>
        <form method="post" action="{{ path('fiona_geek2geek_core_search') }}" id="formid">
            <input type="text" name="gsearch" id="gsearch_bottom" value="{% if gsearchvalue is defined %}{{ gsearchvalue }}{% endif %}" placeholder="Rechercher...">
            <ul>
                <li class="male">
                    <input type="radio" name="ggender" value="MALE" id="gmale" {% if ggendervalue is defined and ggendervalue == 'MALE' %}CHECKED{% endif %}>
                    <label for="gmale">Men</label>
                </li>

                <li class="female">
                    <input type="radio" name="ggender" value="FEMALE" id="gfemale" {% if ggendervalue is defined and  ggendervalue == 'FEMALE' %}CHECKED{% endif %}>
                    <label for="gfemale">Women</label>
                </li>

                <li class="both">
                    <input type="radio" name="ggender" value="BOTH" id="gboth" {% if ggendervalue is defined and (ggendervalue == 'BOTH' or ggendervalue == '') %}CHECKED{% endif %}>
                    <label for="gboth">All</label>
                </li>
            </ul>

            <div id="interets">

                {% for interet in interets %}
                    <div>
                        <input type="checkbox" name="ginteret[]" id="interest_{{ interet.id }}" value="{{ interet.id }}"
                                 {% if indexedInterests[interet.id] is defined %}checked="checked"{% endif %}/>
                        <label for="interest_{{ interet.id }}">
                            {{ interet.label }}
                        </label>
                    </div>
                {% endfor %}

            </div>

            <input type="submit" value="Search" name="valider_recherche" id="valider">
        </form>


    </section>
</aside>


<script>
    jQuery(function($){
        {% if checkedtmpi is defined %}
            {% for impl in checkedtmpi %}
                checkInteret({{ impl }});
            {% endfor %}
        {% endif %}
    });
</script>

src/Fiona/Geek2geek/CoreBundle/Resources/views/Layout/topsearch.html.twig
<aside id="rechercher">
    <form method="post" action="{{ path('fiona_geek2geek_core_search') }}">
        <input type="submit" id="loupe" value="">
        <input type="text" name="gsearch" id="gsearch_top" placeholder="Search...">
        <input type="hidden" name="ggender" value="BOTH">
    </form>
</aside>

<a href="{{ path('fiona_geek2geek_core_homepage') }}">
    <aside id="titre">
        <img src="{{ asset('images/gel.png') }}" width="60"/>
        Geek2geek
    </aside>
</a>
	